const STORAGE_KEY='she-women-curation-v1';
const body=document.body, editor=document.getElementById('editor'), backdrop=document.getElementById('editorBackdrop');
const editable=[...document.querySelectorAll('[data-editable]')];
const frames=[...document.querySelectorAll('[data-media-id]')];
let selected=null, drag=null;

function openEditor(){editor.classList.add('open');backdrop.classList.add('open');editor.setAttribute('aria-hidden','false');body.classList.add('editing');editable.forEach(el=>el.contentEditable='true')}
function closeEditor(){editor.classList.remove('open');backdrop.classList.remove('open');editor.setAttribute('aria-hidden','true');body.classList.remove('editing');editable.forEach(el=>el.contentEditable='false');selectFrame(null)}
document.getElementById('editTrigger').onclick=openEditor;document.getElementById('closeEditor').onclick=closeEditor;backdrop.onclick=closeEditor;
function selectFrame(frame){frames.forEach(f=>f.classList.remove('selected'));selected=frame;const active=!!frame;document.getElementById('replaceButton').disabled=!active;document.getElementById('zoomRange').disabled=!active;document.getElementById('selectedLabel').textContent=active?frame.dataset.mediaId:'None';if(active){frame.classList.add('selected');const z=Math.round((parseFloat(frame.dataset.zoom)||1)*100);document.getElementById('zoomRange').value=z;document.getElementById('zoomOutput').value=z+'%'}}
frames.forEach(frame=>{frame.addEventListener('click',e=>{if(body.classList.contains('editing')){e.preventDefault();selectFrame(frame)}});frame.addEventListener('pointerdown',e=>{if(!body.classList.contains('editing'))return;selectFrame(frame);const img=frame.querySelector('img');const pos=(img.style.objectPosition||'50% 50%').split(' ');drag={frame,img,x:e.clientX,y:e.clientY,px:parseFloat(pos[0]),py:parseFloat(pos[1])};frame.classList.add('dragging');frame.setPointerCapture(e.pointerId)});frame.addEventListener('pointermove',e=>{if(!drag||drag.frame!==frame)return;const r=frame.getBoundingClientRect();const x=Math.max(0,Math.min(100,drag.px+(e.clientX-drag.x)/r.width*100));const y=Math.max(0,Math.min(100,drag.py+(e.clientY-drag.y)/r.height*100));drag.img.style.objectPosition=`${x}% ${y}%`;frame.dataset.x=x;frame.dataset.y=y});frame.addEventListener('pointerup',()=>{frame.classList.remove('dragging');drag=null})});
const imageInput=document.getElementById('imageInput');document.getElementById('replaceButton').onclick=()=>imageInput.click();imageInput.onchange=()=>{const file=imageInput.files[0];if(!file||!selected)return;const reader=new FileReader();reader.onload=()=>{selected.querySelector('img').src=reader.result;selected.dataset.customSrc=reader.result;status('Image replaced — save when ready.')};reader.readAsDataURL(file);imageInput.value=''};
document.getElementById('zoomRange').oninput=e=>{if(!selected)return;const z=e.target.value/100;selected.dataset.zoom=z;selected.querySelector('img').style.transform=`scale(${z})`;document.getElementById('zoomOutput').value=e.target.value+'%'};
document.querySelectorAll('.color-control').forEach(input=>input.oninput=()=>document.documentElement.style.setProperty(input.dataset.color,input.value));
function collect(){return{version:1,text:editable.map((el,i)=>({i,html:el.innerHTML})),media:frames.map(f=>({id:f.dataset.mediaId,src:f.dataset.customSrc||'',x:f.dataset.x||50,y:f.dataset.y||50,zoom:f.dataset.zoom||1})),colors:Object.fromEntries([...document.querySelectorAll('.color-control')].map(i=>[i.dataset.color,i.value]))}}
function apply(data){if(!data)return;(data.text||[]).forEach(x=>{if(editable[x.i])editable[x.i].innerHTML=x.html});(data.media||[]).forEach(x=>{const f=document.querySelector(`[data-media-id="${CSS.escape(x.id)}"]`);if(!f)return;const img=f.querySelector('img');if(x.src){img.src=x.src;f.dataset.customSrc=x.src}img.style.objectPosition=`${x.x}% ${x.y}%`;img.style.transform=`scale(${x.zoom})`;f.dataset.x=x.x;f.dataset.y=x.y;f.dataset.zoom=x.zoom});Object.entries(data.colors||{}).forEach(([k,v])=>{document.documentElement.style.setProperty(k,v);const c=document.querySelector(`[data-color="${k}"]`);if(c)c.value=v})}
function status(msg){const el=document.getElementById('saveStatus');el.textContent=msg;setTimeout(()=>{if(el.textContent===msg)el.textContent=''},3500)}
document.getElementById('saveButton').onclick=()=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify(collect()));status('Saved in this browser.')}catch(e){status('Too much image data. Export settings instead.')}};
document.getElementById('publishButton').onclick=()=>{const clone=document.documentElement.cloneNode(true);clone.querySelector('body').classList.remove('editing');clone.querySelector('#editor').classList.remove('open');clone.querySelector('#editor').setAttribute('aria-hidden','true');clone.querySelector('#editorBackdrop').classList.remove('open');clone.querySelectorAll('[contenteditable]').forEach(el=>el.removeAttribute('contenteditable'));const colors=Object.entries(collect().colors).map(([k,v])=>`${k}:${v}`).join(';');clone.setAttribute('style',colors);const html='<!doctype html>\n'+clone.outerHTML;const blob=new Blob([html],{type:'text/html'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='index.html';a.click();URL.revokeObjectURL(a.href);status('Edited index.html downloaded — upload it to GitHub.')};
document.getElementById('exportButton').onclick=()=>{const blob=new Blob([JSON.stringify(collect(),null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='she-women-site-settings.json';a.click();URL.revokeObjectURL(a.href);status('Settings exported.')};
const configInput=document.getElementById('configInput');document.getElementById('importButton').onclick=()=>configInput.click();configInput.onchange=()=>{const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);apply(data);localStorage.setItem(STORAGE_KEY,JSON.stringify(data));status('Settings imported and saved.')}catch(e){status('That settings file is not valid.')}};if(configInput.files[0])reader.readAsText(configInput.files[0]);configInput.value=''};
document.getElementById('resetButton').onclick=()=>{if(confirm('Reset all text, images and colors to the original site?')){localStorage.removeItem(STORAGE_KEY);location.reload()}};
try{apply(JSON.parse(localStorage.getItem(STORAGE_KEY)))}catch(e){console.warn('Saved settings could not be loaded.')}
document.getElementById('year').textContent=new Date().getFullYear();
